package br.com.challanges.hackerrank.strings;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class AnagramDeletion {
    public static int countDeletions(String s1, String s2) {
        var init = new Date().getTime();
        // Create frequency maps for both strings
        Map<Character, Integer> map1 = getFrequencyMap(s1);
        Map<Character, Integer> map2 = getFrequencyMap(s2);

        // Calculate the number of deletions required
        int deletions = 0;

        for (char c : map1.keySet()) {
            int freq1 = map1.getOrDefault(c, 0);
            int freq2 = map2.getOrDefault(c, 0);
            deletions += Math.abs(freq1 - freq2);
        }

        for (char c : map2.keySet()) {
            if (!map1.containsKey(c)) {
                int freq2 = map2.get(c);
                deletions += freq2;
            }
        }
        System.out.println("time=" + (new Date().getTime() - init)/1000d);
        return deletions;
    }

    private static Map<Character, Integer> getFrequencyMap(String s) {
        Map<Character, Integer> map = new HashMap<>();
        for (char c : s.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }
        return map;
    }

    public static void main(String[] args) {
        String s1 = "abca";
        String s2 = "cdfaaa";
        int deletions = countDeletions("absdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkjabsdjkvuahdakejfnfauhdsaavasdlkj", "djfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfadjfladfhiawasdkjvalskufhafablsdkashlahdfa");
        System.out.println("Minimum number of deletions: " + deletions);
    }
}
